#!/usr/bin/env python3
"""Write the footer timestamp include from the latest Git commit time."""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import subprocess
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default="assets/includes/footer-updated.html")
    parser.add_argument("--timestamp", default=os.environ.get("SITE_LAST_UPDATED", ""))
    return parser.parse_args()


def latest_commit_timestamp() -> str:
    result = subprocess.run(
        ["git", "log", "-1", "--format=%cI"],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def write_include(output_path: pathlib.Path, timestamp: str) -> None:
    timestamp_json = json.dumps(timestamp)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""<!-- Generated by scripts/write_footer_updated_include.py. -->
<script>
window.SITE_LAST_UPDATED = {timestamp_json};

document.addEventListener("DOMContentLoaded", function() {{
  const targets = document.querySelectorAll("[data-last-updated]");
  if (!targets.length || !window.SITE_LAST_UPDATED) return;

  const updatedAt = new Date(window.SITE_LAST_UPDATED);
  if (Number.isNaN(updatedAt.getTime())) return;

  targets.forEach(function(target) {{
    const locale = target.getAttribute("data-locale") || document.documentElement.lang || "en";
    const formatted = new Intl.DateTimeFormat(locale, {{
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "Asia/Shanghai"
    }}).format(updatedAt);

    target.textContent = formatted;
  }});
}});
</script>
""",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    timestamp = args.timestamp or latest_commit_timestamp()
    if not timestamp:
        print("No timestamp available.", file=sys.stderr)
        return 1
    write_include(pathlib.Path(args.output), timestamp)
    print(f"Wrote {args.output} with timestamp {timestamp}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
